apiVersion: cumulusbank.com/v1alpha1
kind: CumulusBankAccSvc
metadata:
  name: accountsvc321
spec:
  replicaCount: 2
  mongodb: 
    host: "mongodb.kubeapp"
    port: "27017"
    username: "YWRtaW4="
    password: "YWRtaW4="
    secret: "aGVsbG8="