kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "accounts-microservice-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage ('build'){
            openshiftBuild(buildConfig: 'account-svc', showBuildLogs: 'true')
          }
          stage ('deploy'){
            openshiftDeploy(deploymentConfig: 'account-svc')
            sleep 10
          }
          stage ('test'){
            openshift.withCluster() {
              openshift.withProject("cumulusbank") {
                 echo "Using project: ${openshift.project()}"
                 def dcObj = openshift.selector('dc', 'account-svc').object()
                 def podSelector = openshift.selector('pod', [deployment: "account-svc-${dcObj.status.latestVersion}"])
                 podSelector.withEach {
                    def podName = it.name()
                    def temparray = podName.split("/")
                    echo "${temparray}"
                    def onlyname = temparray[1]
                    echo "${onlyname}"
                    echo "Running unit tests against ${onlyname}"
                    def execcommand = "oc exec -it ${onlyname} -- /bin/sh -c 'jest --no-color 2> /mnt/a.txt' "
                    script {
                      tempo = sh (script: execcommand, returnStdout: true).trim()
                    }
                    execcommand = "oc exec -it ${onlyname} -- /bin/sh -c 'cat /mnt/a.txt' "
                    echo "${execcommand}"
                    script {
                       tempo = sh (script: execcommand, returnStdout: true).trim()
                    }
                    echo  "var nameee isssss ${tempo}"
                    tempo = tempo.replaceAll("[\n\r]", "")
                    tempo = tempo.split(" ")
                    assert tempo.contains("constructor.PASS")
                 }
              }
            }
          }
        }