kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "accounts-microservice-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage ('build'){
            openshiftBuild(buildConfig: 'account-svc', showBuildLogs: 'true')
          }
          stage ('deploy'){
            openshiftDeploy(deploymentConfig: 'account-svc')
            sleep 10
          }
          stage ('test'){
            openshift.withCluster() {
              openshift.withProject("cumulusbank") {
                 echo "Using project: ${openshift.project()}"
                 def dcObj = openshift.selector('dc', 'account-svc').object()
                 def podSelector = openshift.selector('pod', [deployment: "account-svc-${dcObj.status.latestVersion}"])
                 podSelector.withEach {
                    def podName = it.name()
                    def temparray = podName.split("/")
                    echo "${temparray}"
                    def onlyname = temparray[1]
                    echo "${onlyname}"
                    echo "Running unit tests against ${onlyname}"
                    def cmd = ['/bin/sh',  '-c',  'echo "12345" ']
                    cmd.execute().with{
                        def output = new StringWriter()
                        def error = new StringWriter()
                        it.waitForProcessOutput(output, error)
                        println "error=$error"
                        println "output=$output"
                        println "code=${it.exitValue()}"
                    }
                 }
              }
            }
          }
        }