kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "accounts-microservice-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage ('build'){
            openshiftBuild(buildConfig: 'account-svc', showBuildLogs: 'true')
          }
          stage ('deploy'){
            openshiftDeploy(deploymentConfig: 'account-svc')
            sleep 30
          }
          stage ('test'){
            openshift.withCluster() {
              openshift.withProject("cumulusbank") {
                 echo "Using project: ${openshift.project()}"
                 def dcObj = openshift.selector('dc', 'account-svc').object()
                 def podSelector = openshift.selector('pod', [deployment: "account-svc-${dcObj.status.latestVersion}"])
                 podSelector.withEach {
                    bash '''#!/bin/bash
                    oc get po '''
                    def podName = it.name()
                    def temparray = podName.split("/")
                    echo "${temparray}"
                    def onlyname = temparray[1]
                    echo "${onlyname}"
                    echo "Running unit tests against ${onlyname}"
                    def resp = openshiftExec(pod: onlyname, command: ["/usr/bin/curl"])
                    echo "${resp}"
                 }
              }
            }
          }
        }