kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "accounts-microservice-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage ('build'){
            openshiftBuild(buildConfig: 'account-svc', showBuildLogs: 'true')
          }
          stage ('deploy'){
            openshiftDeploy(deploymentConfig: 'account-svc')
            sleep 10
          }
          stage ('test'){
            openshift.withCluster() {
              openshift.withProject("cumulusbank") {
                 echo "Using project: ${openshift.project()}"
                 def dcObj = openshift.selector('dc', 'account-svc').object()
                 def podSelector = openshift.selector('pod', [deployment: "account-svc-${dcObj.status.latestVersion}"])
                 podSelector.withEach {
                    sh '''#!/bin/bash
                    oc get po '''
                    def podName = it.name()
                    def temparray = podName.split("/")
                    echo "${temparray}"
                    def onlyname = temparray[1]
                    echo "${onlyname}"
                    echo "Running unit tests against ${onlyname}"
                    def execcommand = "oc exec -it ${onlyname} -- npm test | grep PASS"
                    echo "${execcommand}"
                    def temp = sh (script: execcommand, returnStdout: true).trim()
                    echo  "var nameee isssss    ${temp}"
                    def finalchecktemp = temp.split("  ")
                    def finalcheck = finalchecktemp[0]
                    echo "checkkk isssss isssss    ${finalcheck}"
                 }
              }
            }
          }
        }