apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: jenkins_edit
  namespace: cumulusbank
roleRef:
  kind: Role
  name: jenkins
  apiGroup: authorization.openshift.io/v1
subjects:
- kind: ServiceAccount
  name: jenkins
userNames:
- system:serviceaccount:cumulusbank:jenkins