apiVersion: v1
kind: Secret
metadata:
  name: accountmicroservice
  namespace: {{ .Values.metadata.name }} 
  labels:
    app: {{ .Values.metadata.name }} 
type: Opaque
data:
  SECRET: aGVsbG8=
  MONGOUSERNAME: YWRtaW4=
  MONGOPASSWORD: YWRtaW4=