apiVersion: v1
kind: Secret
metadata:
  name: accountmicroservice
  namespace: kubeapp
  labels:
    app: {{ .Values.hpa.metadata.name }}
type: Opaque
data:
  SECRET: aGVsbG8=
  MONGOUSERNAME: YWRtaW4=
  MONGOPASSWORD: YWRtaW4=