apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumulusBankAccSvc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cumulusBankAccSvc
  template:
    metadata:
      labels:
        name: cumulusBankAccSvc
    spec:
      serviceAccountName: cumulusBankAccSvc
      containers:
        - name: cumulusBankAccSvc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cumulusBankAccSvc"
