replicaCount: 2

metadata:
 name: accountsvc 
 label: accountsvc
readinessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
image:
  name: accountsvc
  imageName: "mycluster.icp:8500/default/account-microservice" 
  imagePullPolicy: Always
  ports:
    containerPort: 7000
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "80m"
    memory: "210Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]


envOfSecrets:
  envMONGOUSERNAME:
    name: MONGOUSERNAME
    secretKeyRef:
      name: accountmicroservice
      key: MONGOUSERNAME
  envMONGOPASSWORD:
    name: MONGOPASSWORD
    secretKeyRef:
      name: accountmicroservice
      key: MONGOPASSWORD

ingress:
  metadeta:
    name: accountsvc
  path: /accountsvc
  serviceName: accountsvc
  servicePort: 7000

envOfConfigmaps:
  envMONGOPORT:
    name: MONGOPORT
    configMapKeyRef:
      name: accountmicroservice
      key: MONGOPORT
  envHOSTNAMEMONGODB:
    name: HOSTNAMEMONGODB
    configMapKeyRef:
      name: accountmicroservice
      key: HOSTNAMEMONGODB


hpa:
  metadata:
    name: accountsvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: accountsvc

service:
  serviceMetadata:
    name: accountsvc
    labels:
      app: accountsvc
  selector:
    selectorName: accountsvc
  servicePortConfiguration:
    protocol: TCP
    name: accountsvc
    type: ClusterIP
    port: 7000
    targetPort: 7000