kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
    labels:
        app: "account-svc"
    name: "account-svc"
    annotations:
        description: Keeps track of changes in the application image