apiVersion: v1
kind: Secret
metadata:
  name: accountmicroservice
  namespace: {{ .Values.metadata.name }} 
  labels:
    app: {{ .Values.metadata.name }} 
type: Opaque
data:
  SECRET: {{ .Values.mongodb.secret }}
  MONGOUSERNAME: {{ .Values.mongodb.username }}
  MONGOPASSWORD: {{ .Values.mongodb.password }}