apiVersion: v1
kind: Secret
metadata:
  name: "accountmicroservice"
  labels:
    app: "account-svc"
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  SECRET: "{{ .Values.mongodb.secret }}"
  MONGOUSERNAME: "{{ .Values.mongodb.username }}"
  MONGOPASSWORD: "{{ .Values.mongodb.password }}"