apiVersion: v1
kind: Service
metadata:
 name: "account-svc"
 labels:
   app: "account-svc"
spec:
 type: {{ .Values.service.servicePortConfiguration.type}}
 selector:
   app: {{ .Values.service.selector.selectorName }}
 ports:
  - protocol: {{ .Values.service.servicePortConfiguration.protocol}}
    name: {{ .Values.service.servicePortConfiguration.name}}
    port: {{ .Values.service.servicePortConfiguration.port}}
    targetPort: {{ .Values.service.servicePortConfiguration.targetPort}}