replicaCount: 2
namespace: kubeapp
metadata:
 name: accountsvc 
 label: accountsvc
readinessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
mongodb:
  host: "mongodb.kubeapp"
  port: "27017"
  username: "YWRtaW4="
  password: "YWRtaW4="
  secret: "aGVsbG8="
livenessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
image:
  name: accountsvc
  imageName: "accountsvc" 
  imagePullPolicy: Always
  ports:
    containerPort: 7000
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "80m"
    memory: "210Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]


envOfSecrets:
  envMONGOUSERNAME:
    name: MONGOUSERNAME
    secretKeyRef:
      name: accountmicroservice
      key: MONGOUSERNAME
  envMONGOPASSWORD:
    name: MONGOPASSWORD
    secretKeyRef:
      name: accountmicroservice
      key: MONGOPASSWORD

envOfConfigmaps:
  envMONGOPORT:
    name: MONGOPORT
    configMapKeyRef:
      name: accountmicroservice
      key: MONGOPORT
  envHOSTNAMEMONGODB:
    name: HOSTNAMEMONGODB
    configMapKeyRef:
      name: accountmicroservice
      key: HOSTNAMEMONGODB


hpa:
  metadata:
    name: accountsvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: accountsvc

service:
  serviceMetadata:
    name: accountsvc
    labels:
      app: accountsvc
  selector:
    selectorName: accountsvc
  servicePortConfiguration:
    protocol: TCP
    name: accountsvc
    type: ClusterIP
    port: 7000
    targetPort: 7000

imagestream:
  name:  accountsvc
  label: accountsvc

buildconfig:
  uri: "https://github.com/cumulus-bank/Accounts-Microservice.git"
  branch: "master"
  name: "accountsvc"
  imagename: "accountsvc:latest"
  secret1: "secret1"
  secret2: "secret2"

routes:
  host: "accountsvc-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 7000
  name: accountsvc
  weight: 100